### ISSUE TITLE
Early release observations

### ISSUE THREAD

**Issue by XvSkItZvX** [osum4est/the-bom-plugin#1] opened 2017-07-31 04:51 UTC
I keep a package of "barely more than vanilla" I use to test mods the provide information, change the interface, etc. There are actually quite a few however they add no real content to vanilla Minecraft outside of aesthetics and quality of life tweaks. 

I was also the first to post on the project page in Curseforge. 

I installed the mod and it appeared to work for the most part, on a couple of the simpler vanilla recipes with only a couple of issues I'll address in a moment as they are somewhat minor. When I checked a more complex recipe, "Minecart with TNT" (minecraft:tnt_minecart) specifically, I was provided with images of the three items that are required to craft. However, only the sand used to craft the TNT was properly numbered under the graphic.

On mousing over each item the tool tip did display the quantity needed to craft the items. 

Upon checking the recipes for the "Minecart" and "TNT" separately I noticed that only the sand displayed the quantity under the image, with the tooltip being accurate, as well. 

Outside of the missing quantities, I am using a 44" monitor @ 1920x1080 resolution on "GUI Scale: Normal" and the graphics and text were quite small, compared to the rest of the item interfaces, with the images sitting over the text in a few cases.

A possible contributor to text issues within my pack may be the ["TrueType Font Replacement"](https://minecraft.curseforge.com/projects/truetype-font-replacement) mod that I use to replace the gaudy native vanilla font. 

I hope to see this mod become everything you envisioned, it is a much needed tool and I'm sure that, with all the rabbit hole mods out there, the community will greatly appreciate your efforts. If there is anything more information I can provide feel free to let me know.

**Comment by FancyFurret** [comment] 2017-07-31 04:59
Thanks for the feedback! To clarify: is the number being shown at all for gunpower or iron, or is it just hard to read? I've installed the TrueType mod and it does seem to distort the number '5.

**Comment by XvSkItZvX** [comment] 2017-07-31 05:01
It does display a numeric value...not always accurate but there is at least a "0" or higher.

**Comment by FancyFurret** [comment] 2017-07-31 05:04
Got it, as long as the tooltips are displaying the correct number (which they are for me), then this seems to be an issue with scaling the TrueType font down. I will play around with the scale tomorrow and see if it can be fixed by making the numbers slightly bigger. If not, I can add a config option that lets you set the text scale back to normal size.

Edit: Confirmed that the issue is scaling down the TrueType font as the Refined Storage grid has the exact same issue.

**Comment by XvSkItZvX** [comment] 2017-07-31 05:06
Awesome, the Tooltips are as they should be for me as well. Look forward to the next release, thanks!

**Comment by FancyFurret** [comment] 2017-07-31 20:51
Added config file with option to change text scale in commit #7ae8b25. Setting this option to .75 or higher seems to make the numbers readable with TTFR. Closing issue

**Closed as completed by FancyFurret** 2017-07-31 20:51 UTC
Labels: bug

**Comment by FancyFurret** [comment] 2017-08-02 18:39
Just pushed a new version to curse, it's processing now but should be done soon!

**Comment by XvSkItZvX** [comment] 2017-08-02 20:14
Awesome! Worked beautifully, The default was an immediate improvement however I found that .75 was preferable for me personally and I'm sure other players will be able find settings they are comfortable with as well. 

I doubt another issue that presented when I began to test the update had anything to do with your mod at all and more likely cause I got sloppy in my testing instance. I feel I should give a heads up just in case. After installing the updated mod I attempted to load into my test world instead hanging and being told that the server couldn't keep up in the console before being forcibly closed. This resolved by creating a new instance and installing all mods/configs from the previous instance (including the updated mod) and everything worked  beautifully. As I said I strongly doubt this had anything to do with your mod but an error on my part. 

Thanks for the quick response and working out the issue. If you ever need or want someone to help test a project feel free to get a hold of me.

**Comment by FancyFurret** [comment] 2017-08-02 22:36
Interesting, thanks for letting me know! I shouldn't be from my mod, but if it keeps happening definitely let me know, and post the log.

This is my first mod I've released so I think I'll stick with this for awhile until I'm confident there aren't any major bugs, and there are a few features I may want to implement. (Possibly using recipes from other machines, and the ability to show the ingredients needed in-game so you don't have to keep opening up JEI).

Thanks again for letting me know of this issue, and it would be awesome if you could let me know of any more you run into!

**Comment by XvSkItZvX** [comment] 2017-08-02 22:37
Gladly! Will do.
